#!/bin/sh
# git hook "prepare-commit-msg"

# args:
# - `$1`: commit message file
# - `$2`: commit source
# - `$3`: commit hash(sha1)

# ref. https://git-scm.com/docs/githooks

readonly COMMIT_MESSAGE_FILE="$1"
readonly COMMIT_MESSAGE="$(cat "$1")"
readonly PREFIX="${COMMIT_MESSAGE%%:*}"
readonly COMMIT_SOURCE="$2"

add_emoji() {
  echo "$1 $COMMIT_MESSAGE" > "$COMMIT_MESSAGE_FILE"
}

case "$COMMIT_SOURCE" in
  message) # `-m` or `-F`
    case "$PREFIX" in
      init) add_emoji ":tada:" ;;
      refact) add_emoji ":recycle:" ;;
      fix) add_emoji ":lady_beetle:" ;;
      feat|new) add_emoji ":sparkles:" ;;
      doc) add_emoji ":memo:" ;;
      typo) add_emoji ":pencil2:" ;;
      perf) add_emoji ":zap:" ;;
      env|conf) add_emoji ":wrench:" ;;
      delete|del) add_emoji ":fire:" ;;
      image|img) add_emoji ":camera:" ;;
      upgrade) add_emoji ":rocket:" ;;
      test) add_emoji ":white_check_mark:" ;;
    esac
    ;;
  merge) # merge or `.git/MERGE_MSG` exists
    add_emoji ":shuffle_tracks_button:"
    ;;
  template) # `-t`
    ;;
  sqush) # `.git/SQUSH_MSG` exists
    ;;
  commit) # `-c`, `-C` or `--amend`
    ;;
  *)
    ;;
esac
